### PR TITLE
Fixed a few macros in configure.ac that failed to create generic/config.h, further elaboration of examples

### PR DESCRIPTION
**Pull request by mxmanghi**
On Ubuntu/minotaur autoreconf complained that a macro was called in the wrong sequence. This could be related to the new versions of autotools available. The client.tcl/server.tcl examples were expanded highlighting the asynchronous organization of the code and adding messaging. The client.tcl example can work as a playground to experiment what happens when some events occur

### CODE REVIEW

**Comment by cyanogilvie** [comment]
Thanks for the PR, just a few things:
- I like the expanded examples, but I'd prefer to keep the hello-world ones as they are (as absolutely minimal as possible) - their intent is to convey the essential elements and leave off as much non-essential detail as possible.  Could you split off the new examples into a new client and server set of files?
- What is the requirement for a VERSION file?

**Comment by mxmanghi** [comment]
I restored the client.tcl and server.tcl examples in their original form. I think the only relevant change is tclsh having now its generic name, instead of referencing 8.5 explicitly. I named the new examples client-asynch.tcl and server-asynch.tcl. Comments in these examples were further elaborated. If you could consider to release the code I volunteer to package it for Debian/Ubuntu

**Comment by cyanogilvie** [comment]
I'm still not clear on the purpose of the VERSION file - I'd prefer not to have another place where the version is hard-coded.  If there is something that needs it, I'd prefer to make it a generated file, from the value specified in the configure.ac

**Comment by mxmanghi** [comment]
Never mind, it's OK the way you like it.

 -- Massimo

**Comment by cyanogilvie** [comment]
Ok, I've merged the PR, and released version 0.3.  For releases I generally just create a version tag (`v0.3` in this case).  They're not really releases in the github sense, but that's enough to be able to fetch the source for that version.

Do you need an actual github release to package it?

**Comment by mxmanghi** [comment]
I don't think so, I guess the URL pattern to the tag is enough. They have
heuristics of rules for matching stuff on github and detect new releases
when they occur. They do require an upstream contact email though. Would
you send me your email for this matter?

 -- Massimo

**Comment by cyanogilvie** [comment]
I'm not so keen on publishing my private email address in a github comment (or in package metadata) where it's likely to be spammed or abused.  Is there a way to use the issue tracker on this project instead?

**Comment by mxmanghi** [comment]
I understand. All of us are wary in this respect but Debian doesn't publish
this information on their package information directory. The only email I
can see on the package information pages are the maintainer email addresses
(my email in this case). Your email would appear in the preformatted
message that is automatically to be sent to the debian-devel mailing list
announcing my intention to package your software. I don't know if I can
eschew this information with a URL pointing to the issue tracker: everybody
would see it and I expect the service that handles the "intent to package"
message to parse every form field (I'm sure it's done for other fields in
the same form). I will ask some Debian developer

 -- Massimo

**Pull request merged**
